// functions/index.js
// Simple 1st-gen callable function for "fake" audio processing

const functions = require("firebase-functions");
const admin = require("firebase-admin");

// Initialize the Admin SDK once per instance
if (!admin.apps.length) {
  admin.initializeApp();
}

exports.processAudioFile2 = functions.https.onCall(async (data, context) => {
  console.log("processAudioFile2 called with data:", data);

  // 1. Auth check
  if (!context.auth || !context.auth.uid) {
    console.error("Unauthenticated call to processAudioFile2");
    throw new functions.https.HttpsError(
      "unauthenticated",
      "User must be logged in to process audio.",
    );
  }

  const userId = context.auth.uid;

  // 2. Accept either docId or docID (matches FlutterFlow param name)
  const docId = data.docId || data.docID;
  if (!docId || typeof docId !== "string") {
    console.error("Missing or invalid docId/docID in processAudioFile2:", data);
    throw new functions.https.HttpsError(
      "invalid-argument",
      "docId (or docID) is required and must be a string.",
    );
  }

  // 3. Reference to the Firestore document in top-level "audioNotes"
  const docRef = admin.firestore().collection("audioNotes").doc(docId);
  console.log("Target document path:", docRef.path, "for user:", userId);

  // (Optional) ensure the document exists before updating
  const snap = await docRef.get();
  if (!snap.exists) {
    console.error("Document does not exist at path:", docRef.path);
    throw new functions.https.HttpsError(
      "not-found",
      `Document ${docId} not found in audioNotes.`,
    );
  }

  // 4. Mark as "processing"
  await docRef.update({
    status: "processing",
    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  });
  console.log('Status set to "processing" for', docRef.path);

  // 5. Fake "heavy work" (e.g., STT + AI). Here we just wait 2 seconds.
  await new Promise((resolve) => setTimeout(resolve, 2000));

  const mockTranscript = `
This is a fake transcript generated by the processAudioFile2 Cloud Function.

In the real version, this text will come from a Speech-to-Text API
and an AI model that turns it into structured notes.

Doc ID: ${docId}
User ID: ${userId}
Generated at: ${new Date().toISOString()}
  `.trim();

  // 6. Mark as "processed" and save the mock transcript
  await docRef.update({
    status: "processed",
    transcript: mockTranscript,
    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  });
  console.log(
    'Status set to "processed" and transcript written for',
    docRef.path,
  );

  // 7. Return a tiny response for debugging in FlutterFlow if needed
  return {
    success: true,
    docPath: docRef.path,
    message: "processAudioFile2 completed successfully.",
  };
});
